version: "3.8"

services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "9222:9222"
    command: "-js"
    volumes:
      - nats-data:/data
    networks:
      - nats-network

  nats-box:
    image: natsio/nats-box:latest
    depends_on:
      - nats
    networks:
      - nats-network
    entrypoint: ["tail", "-f", "/dev/null"]

volumes:
  nats-data:

networks:
  nats-network:
    driver: bridge
