spring.application.name=NAT_Reliability_Demo

# NATS Configuration
nats.url=nats://localhost:4222
nats.subject=notifications.test
nats.stream=NOTIFICATIONS
nats.dlq-stream=NOTIFICATIONS_DLQ
nats.dlq-subject=notifications.dlq

# Consumer Configuration
nats.consumer.name=demo-consumer
nats.consumer.durable=demo-consumer-durable
nats.consumer.maxDeliver=3
nats.consumer.retryWaitSeconds=2

# API Configuration
server.port=8080
